export interface ILocationInventory{
    ID:number;
    Title:string;
    Week:string;
    LocationId:number;
    LocationTitle:string;
    Areainacres:string;
    Builtupofficespacearea:string;
    Cubicleinventory:string;
    Cabininventory:string;
    Cubicleoccupied:string;
    Cabinoccupied:string;
    Employee:string;
    Totalstaff:string;
    Townshipaccommodation:string;
    GHtransitaccommodation:string;
    GETaccommodation:string;
    Mealserved:string;
    Dailybuses:string;
    Monthlyhirecar:string;
}